apiVersion: v1
kind: Secret
metadata:
  name: credenciales-manifest
type: Opaque
data:
  # estas codificadas en base64 para evitar signos raro
  username: YWRtaW4=
  password: aG9sYXF1ZXRhbAo=
  password: MTIzNTZhYmNkIAo=