apiVersion: v1
kind: Pod
metadata:
  name: nginx-secrets-mount-item
spec:
  containers:
    - name: nginx
      image: nginx:1.7.9
      volumeMounts:
        - name: secrets
          mountPath: "/etc/secrets"
          readOnly: true
  volumes:
    - name: secrets
      secret: #origen
        secretName: credenciales-manifest #nombre
        items: #items que queremos import
          - key: password # clave
            path: password # el so se llamara
            mode: 500 # modo de acceso
